### ISSUE TITLE
Component missing from installer

### ISSUE THREAD

**Issue by simonbagley** [QuasarApp/CQtDeployer#614]
I have just tried this again, with release 1.5, and I get the same error when trying to run the installed application on the target PC:
`simon@ubuntu:~/pure-qml/pure-qml$ ./pure-qml.sh QML debugging is enabled. Only use this in a safe environment. QQmlApplicationEngine failed to load component qrc:/qml/main.qml:60:5: Type CompositorScreen unavailable qrc:/qml/CompositorScreen.qml:58:5: ListModel is not a type ^C`
Maybe it is a problem with my json file?

_Originally posted by @simonbagley in https://github.com/QuasarApp/CQtDeployer/issues/600#issuecomment-846847767_

**Comment by EndrII** [comment]
hm.
Show me please your cqtdeployer version.
```
cqtdeployer v 
```
and tree of the deployed application.
```bash
tree DistributionKit
```

**Comment by simonbagley** [comment]
```
simon@ubuntu:~/pure-qml$ cqtdeployer v
Info: Print info ...
CQtDeployer: 1.5.0.35 *** Binary Box ***
Qt: 5.15.0
QSettings::setValue: Empty key passed
```

**Comment by simonbagley** [comment]
```
simon@ubuntu:~/Qt/Examples/Qt-6.1.0/wayland/build-pure-qml-Desktop_Qt_6_1_0_GCC_64bit-Debug$ tree DeploymentPackage/
DeploymentPackage/
├── Installerpure-qml.run
├── Installerpure-qml.run.md5
├── plugins
└── qml
    ├── QtQuick
    │   ├── Controls
    │   └── NativeStyle
    ├── QtQuick3D
    └── QtWayland
        └── Compositor

```

**Comment by EndrII** [comment]
please update to cqtdeployer 1.5.0.36 
run the 
```
snap refresh 

```

**Comment by simonbagley** [comment]
I have run snap refresh:
`simon@ubuntu:~/Qt/Examples/Qt-6.1.0/wayland/build-pure-qml-Desktop_Qt_6_1_0_GCC_64bit-Debug$ snap refresh
cqtdeployer 1.5.0.36 from QuasarApp group (quasarrapp) refreshed
`

`cqtdeployer v `still shows the following:
```
simon@ubuntu:~/pure-qml$ cqtdeployer v
Info: Print info ...
CQtDeployer: 1.5.0.35 *** Binary Box ***
Qt: 5.15.0
QSettings::setValue: Empty key passed
```
When I run the deployed application, I still get the same error message.

**Comment by simonbagley** [comment]
`snap list cqtdeployer` shows the correct version:
```
simon@ubuntu:~/pure-qml$ snap list cqtdeployer
Name         Version   Rev  Tracking       Publisher   Notes
cqtdeployer  1.5.0.36  210  latest/stable  quasarrapp  -
```

**Comment by EndrII** [comment]
mh it is my output.  
```bash
:~$ cqtdeployer v
Info: Print info ...
CQtDeployer: 1.5.0.36 *** Binary Box ***
Qt: 5.15.0

```
maybe you have an another version of the cqtdeployer. for example deb or installer.

**Comment by EndrII** [comment]
i have some error. its very strange. 
please wait

**Comment by simonbagley** [comment]
I have removed cqtdeployer completely, and re-installed with snap. The correct version is now reported:
`simon@ubuntu:~/pure-qml$ cqtdeployer v
Info: Print info ...
CQtDeployer: 1.5.0.36 *** Binary Box ***
Qt: 5.15.0
QSettings::setValue: Empty key passed
`

I am now getting a different error message when trying to run the deployed application:
```
simon@ubuntu:~/pure-qml$ ./pure-qml.sh 
QML debugging is enabled. Only use this in a safe environment.
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in "/home/simon/pure-qml/plugins/platforms:"
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
```

**Comment by EndrII** [comment]
done 
please update cqtdeployer and try deploy tour application again.

**Comment by EndrII** [comment]
@simonbagley any feedback please

**Comment by simonbagley** [comment]
@EndrII I have updated CQtDeployer and still get the last error shown above. I have shown the error again below, along with the output from cqtdeployer v

```
simon@ubuntu:~/pure-qml$ ./pure-qml.sh 
QML debugging is enabled. Only use this in a safe environment.
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in "/home/simon/pure-qml/plugins/platforms:"
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

```
simon@ubuntu:~/pure-qml$ cqtdeployer v
Info: Print info ...
CQtDeployer: 1.5.0.37 *** Binary Box ***
Qt: 5.15.0
QSettings::setValue: Empty key passed
```

**Comment by EndrII** [comment]
Please redeploy your application without qif option and show me tree of the DestributionKit/plugins folder.

**Comment by simonbagley** [comment]
I have re-deployed with the qif option set to false. The tree of the deployment package plugins folder is as follows:

```
simon@ubuntu:~/Qt/Examples/Qt-6.1.0/wayland/build-pure-qml-Desktop_Qt_6_1_0_GCC_64bit-Debug$ tree DeploymentPackage/plugins/
DeploymentPackage/plugins/

0 directories, 0 files
```
i.e. it is empty.

**Comment by EndrII** [comment]
show me deploy log please 
run cqtdeployer with the -verbose 3 option.

**Comment by simonbagley** [comment]
Here is the deploy log:
[cqtdeployer.log](https://github.com/QuasarApp/CQtDeployer/files/6538040/cqtdeployer.log)

**Comment by EndrII** [comment]
does cqtdeployer have access to the qt6 folder?

**Comment by EndrII** [comment]
try run this commands:
```
 sudo snap connect cqtdeployer:process-control 
 sudo snap connect cqtdeployer:removable-media
 sudo snap connect cqtdeployer:system-backup
```

**Comment by simonbagley** [comment]
How can I check if cqtdeployer has access to the qt6 folder?
I have run the `sudo snap connect` commands, and the deployment folder still has no files in the plugins directory, and the deployed application produces the same error as before.

**Comment by EndrII** [comment]
just run the cqtdeployer in debug mode 
```bash
snap run --shell cqtdeployer
```

and open your qt directory 
```
cd /home/simon/Qt/6.1.0/gcc_64/bin/
ll
```

**Comment by simonbagley** [comment]
I have run cqtdeployer in debug mode, and can access the qt directory.
ls -l shows all of the files.

**Comment by simonbagley** [comment]
```
simon@ubuntu:/home/simon/Qt/6.1.0/gcc_64/bin$ ls -l
total 574884
-rwxr-xr-x 1 simon simon   196920 May  3 06:10 androiddeployqt
-rw-r--r-- 1 simon simon  3235256 May  3 05:55 androiddeployqt.debug
-rwxr-xr-x 1 simon simon    48584 May  3 06:10 androidtestrunner
-rw-r--r-- 1 simon simon  1400576 May  3 06:08 androidtestrunner.debug
-rwxr-xr-x 1 simon simon  1127160 May  4 05:12 assistant
-rw-r--r-- 1 simon simon 26519192 May  4 05:11 assistant.debug
-rwxr-xr-x 1 simon simon    40440 May  4 06:12 balsam
-rw-r--r-- 1 simon simon  1276840 May  4 06:12 balsam.debug
-rwxr-xr-x 1 simon simon   563904 May  4 05:12 designer
-rw-r--r-- 1 simon simon 20033152 May  4 05:12 designer.debug
-rwxr-xr-x 1 simon simon   332272 May  4 05:12 lconvert
-rw-r--r-- 1 simon simon 10414768 May  4 05:11 lconvert.debug
-rwxr-xr-x 1 simon simon   110504 May  4 08:37 licheck64
-rwxr-xr-x 1 simon simon  1093304 May  4 05:12 linguist
-rw-r--r-- 1 simon simon 30452296 May  4 05:11 linguist.debug
-rwxr-xr-x 1 simon simon   389928 May  4 05:12 lrelease
-rw-r--r-- 1 simon simon 12217872 May  4 05:11 lrelease.debug
-rwxr-xr-x 1 simon simon 31839432 May  4 05:12 lupdate
-rw-r--r-- 1 simon simon 47600560 May  4 05:11 lupdate.debug
-rwxr-xr-x 1 simon simon    27728 May  4 06:12 meshdebug
-rw-r--r-- 1 simon simon  1038408 May  4 06:10 meshdebug.debug
-rwxr-xr-x 1 simon simon    70328 May  4 05:12 pixeltool
-rw-r--r-- 1 simon simon  2679624 May  4 05:11 pixeltool.debug
-rwxr-xr-x 1 simon simon    87304 May  4 05:12 qdbus
-rw-r--r-- 1 simon simon  2024248 May  4 05:11 qdbus.debug
-rwxr-xr-x 1 simon simon   340312 May  3 06:10 qdbuscpp2xml
-rw-r--r-- 1 simon simon  8433608 May  3 05:55 qdbuscpp2xml.debug
-rwxr-xr-x 1 simon simon   161592 May  4 05:12 qdbusviewer
-rw-r--r-- 1 simon simon  5620472 May  4 05:11 qdbusviewer.debug
-rwxr-xr-x 1 simon simon    77472 May  3 06:10 qdbusxml2cpp
-rw-r--r-- 1 simon simon  2077752 May  3 05:55 qdbusxml2cpp.debug
-rwxr-xr-x 1 simon simon   149800 May  4 05:12 qdistancefieldgenerator
-rw-r--r-- 1 simon simon  5365648 May  4 05:11 qdistancefieldgenerator.debug
-rwxr-xr-x 1 simon simon 57929600 May  4 05:12 qdoc
-rw-r--r-- 1 simon simon 78447968 May  4 05:11 qdoc.debug
-rwxr-xr-x 1 simon simon   193344 May  4 05:12 qhelpgenerator
-rw-r--r-- 1 simon simon  6270224 May  4 05:11 qhelpgenerator.debug
-rwxr-xr-x 1 simon simon  2917208 May  3 06:10 qmake
-rw-r--r-- 1 simon simon 73376848 May  3 06:10 qmake.debug
-rwxr-xr-x 1 simon simon  2917208 May  3 06:10 qmake6
-rwxr-xr-x 1 simon simon    91568 May  3 19:57 qml
-rw-r--r-- 1 simon simon  2639096 May  3 19:56 qml.debug
-rwxr-xr-x 1 simon simon   816224 May  3 19:57 qmlcachegen
-rw-r--r-- 1 simon simon 19246944 May  3 19:56 qmlcachegen.debug
-rwxr-xr-x 1 simon simon   136408 May  3 19:57 qmleasing
-rw-r--r-- 1 simon simon  5038480 May  3 19:57 qmleasing.debug
-rwxr-xr-x 1 simon simon   454464 May  3 19:57 qmlformat
-rw-r--r-- 1 simon simon  9031736 May  3 19:56 qmlformat.debug
-rwxr-xr-x 1 simon simon   422440 May  3 19:57 qmlimportscanner
-rw-r--r-- 1 simon simon  8167992 May  3 19:56 qmlimportscanner.debug
-rwxr-xr-x 1 simon simon  1082336 May  3 19:57 qmllint
-rw-r--r-- 1 simon simon 28901928 May  3 19:56 qmllint.debug
-rwxr-xr-x 1 simon simon   172864 May  3 19:57 qmlplugindump
-rw-r--r-- 1 simon simon  5459048 May  3 19:57 qmlplugindump.debug
-rwxr-xr-x 1 simon simon   256752 May  3 19:57 qmlpreview
-rw-r--r-- 1 simon simon  9537592 May  3 19:56 qmlpreview.debug
-rwxr-xr-x 1 simon simon   388784 May  3 19:57 qmlprofiler
-rw-r--r-- 1 simon simon 14564352 May  3 19:56 qmlprofiler.debug
-rwxr-xr-x 1 simon simon    53288 May  3 19:57 qmlscene
-rw-r--r-- 1 simon simon  1836888 May  3 19:57 qmlscene.debug
-rwxr-xr-x 1 simon simon     6976 May  3 19:57 qmltestrunner
-rw-r--r-- 1 simon simon  1307200 May  3 19:57 qmltestrunner.debug
-rwxr-xr-x 1 simon simon    28408 May  3 19:57 qmltime
-rw-r--r-- 1 simon simon  3127064 May  3 19:57 qmltime.debug
-rwxr-xr-x 1 simon simon   139240 May  3 19:57 qmltyperegistrar
-rw-r--r-- 1 simon simon  4513008 May  3 19:55 qmltyperegistrar.debug
-rwxr-xr-x 1 simon simon    61160 May  3 11:36 qsb
-rw-r--r-- 1 simon simon  1536592 May  3 11:36 qsb.debug
-rwxr-xr-x 1 simon simon   409904 May  4 05:07 qscxmlc
-rw-r--r-- 1 simon simon 11120536 May  4 05:07 qscxmlc.debug
-rwxr-xr-x 1 simon simon      651 May  3 05:47 qt-cmake
-rwxr-xr-x 1 simon simon      660 May  3 05:47 qt-cmake-private
-rw-r--r-- 1 simon simon      984 May  3 05:47 qt-cmake-private-install.cmake
-rwxr-xr-x 1 simon simon      188 May  3 05:47 qt-cmake-standalone-test
-rwxr-xr-x 1 simon simon      739 May  3 05:47 qt-configure-module
-rw-rw-rw- 1 simon simon       85 May 11 15:07 qt.conf
-rwxr-xr-x 1 simon simon   110440 May  4 05:12 qtattributionsscanner
-rw-r--r-- 1 simon simon  3912872 May  4 05:11 qtattributionsscanner.debug
-rwxr-xr-x 1 simon simon    79416 May  4 05:12 qtdiag
-rw-r--r-- 1 simon simon  2657328 May  4 05:11 qtdiag.debug
-rwxr-xr-x 1 simon simon    79416 May  4 05:12 qtdiag6
-rwxr-xr-x 1 simon simon    31968 May  4 05:12 qtpaths
-rw-r--r-- 1 simon simon  1038016 May  4 05:11 qtpaths.debug
-rwxr-xr-x 1 simon simon    23824 May  4 05:12 qtplugininfo
-rw-r--r-- 1 simon simon  1007352 May  4 05:11 qtplugininfo.debug
-rwxr-xr-x 1 simon simon    68784 May  4 05:59 qtwaylandscanner
-rw-r--r-- 1 simon simon  1600624 May  4 05:58 qtwaylandscanner.debug
-rwxr-xr-x 1 simon simon   250104 May  4 06:12 shadergen
-rw-r--r-- 1 simon simon  7983192 May  4 06:12 shadergen.debug
```

**Comment by EndrII** [comment]
i still do not understand what happens, so i recommend for you use the cqtdeployer from installer as a temp solution of your problem.

**Comment by simonbagley** [comment]
I'm not sure what you mean by "use the cqtdeployer from installer".

**Comment by pzhlkj6612** [comment]
> the cqtdeployer from installer

Hi @simonbagley . I guess @EndrII means you can try the “.deb” or “.run” installer downloaded from the [Release](https://github.com/QuasarApp/CQtDeployer/releases) page.

**Comment by simonbagley** [comment]
@pzhlkj6612 Thanks for clarifying.
I have tried the ".run" installer, and the deployment package is generated, but when I try to run the deployed application, I get an error regarding failure to load a component:
```
QML debugging is enabled. Only use this in a safe environment.
QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:60:5: Type CompositorScreen unavailable
qrc:/qml/CompositorScreen.qml:58:5: ListModel is not a type
```
The application then just hangs and does not display the compositor window.
If I run the application from within Qt Creator, or run the application created from Qt Creator, this works as expected, by displaying the compositor window.

**Comment by simonbagley** [comment]
The problem appears to be related to Qt Wayland, as when I use CQtDeployer to create a deployment package for another application, such as the Qt widgets demo "wiggly", the deployed application works fine.

**Comment by EndrII** [comment]
> @pzhlkj6612 Thanks for clarifying.
> I have tried the ".run" installer, and the deployment package is generated, but when I try to run the deployed application, I get an error regarding failure to load a component:
> 
> ```
> QML debugging is enabled. Only use this in a safe environment.
> QQmlApplicationEngine failed to load component
> qrc:/qml/main.qml:60:5: Type CompositorScreen unavailable
> qrc:/qml/CompositorScreen.qml:58:5: ListModel is not a type
> ```
> 
> The application then just hangs and does not display the compositor window.
> If I run the application from within Qt Creator, or run the application created from Qt Creator, this works as expected, by displaying the compositor window.

You install online or offline installer ?
if you install offline version you have old version without last hot fixes.

**Comment by simonbagley** [comment]
@EndrII So unfortunately, reverting back to using the earlier version is not a solution for the Qt Wayland demo I am trying to use.

**Comment by simonbagley** [comment]
I used the offline installer. ok, I'll try again with the online .run installer.

**Comment by EndrII** [comment]
> The problem appears to be related to Qt Wayland, as when I use CQtDeployer to create a deployment package for another application, such as the Qt widgets demo "wiggly", the deployed application works fine.

no, trouble in the qml list model. it is already fixed. 
show me your version cqtdeployer that you install from .run installer.

**Comment by EndrII** [comment]
> @EndrII I have updated CQtDeployer and still get the last error shown above. I have shown the error again below, along with the output from cqtdeployer v
> 
> ```
> simon@ubuntu:~/pure-qml$ ./pure-qml.sh 
> QML debugging is enabled. Only use this in a safe environment.
> qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in "/home/simon/pure-qml/plugins/platforms:"
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> ```
> 
> ```
> simon@ubuntu:~/pure-qml$ cqtdeployer v
> Info: Print info ...
> CQtDeployer: 1.5.0.37 *** Binary Box ***
> Qt: 5.15.0
> QSettings::setValue: Empty key passed
> ```

And this issue it is another trouble of the snap package.

**Comment by simonbagley** [comment]
I have reinstalled cqtdeployer from the ".run" installer (https://github.com/QuasarApp/CQtDeployer/releases/download/1.5.0/CQtDeployer_1.5_Installer_Linux64.run).
Now when I create a deployment package for the Qt Wayland pure-QML demo, and then run the deployed package, it now works as expected :-)

cqtdeployer v reports the following:
```
Info: Print info ...
CQtDeployer: 1.5.0.37 *** Binary Box ***
Qt: 5.15.0
QSettings::setValue: Empty key passed
```

**Comment by EndrII** [comment]
@simonbagley  congratulations !!!)

but i still have one open issue with the snap version. 
You can tell in more detail what actions you did when installing the snap version of cqtdeployer.

**Comment by simonbagley** [comment]
These are the steps I followed when installing the snap version:

1. Make sure no other versions of cqtdeployer are installed. i.e. .deb, .run, or snap.

2. Download the snap deployment package from: https://github.com/QuasarApp/CQtDeployer/releases/download/1.5.0/cqtdeployer_1.5.0.35_amd64.snap

3. Install the cqtdeployer package from the snap file: 
```
snap install ~/Downloads/cqtdeployer_1.5.0.35_amd64.snap 
cqtdeployer 1.5.0.35 from QuasarApp group (quasarrapp) installed
```

4.  Enable permissions for cqtdeployer:
```
sudo snap connect cqtdeployer:process-control
sudo snap connect cqtdeployer:removable-media
sudo snap connect cqtdeployer:system-backup
```
5. Check version of cqtdeployer: `cqtdeployer v`
This command didn't work, it produced the error message:
`bash: /home/simon/.local/bin/cqtdeployer: No such file or directory`
To get this command to work, I had to run: `/snap/cqtdeployer/current/cqtdeployer.sh v`, which produced the output:
```
Info: Print info ...
CQtDeployer: 1.5.0.35 *** Binary Box ***
Qt: 5.15.0
QSettings::setValue: Empty key passed
```

6. Open Qt creator (Qt6), and open the Qt Wayland pure-qml example. Build the pure-qml application.

7. Navigate to the build directory for pure-qml. (in my case: /`home/simon/Qt/Examples/Qt-6.1.0/wayland/build-pure-qml-Desktop_Qt_6_1_0_GCC_64bit-Debug`)

8. Create an options JSON file for cqtdeployer: `deployment.json`, as follows:
```
{
    "clear": true,
    "deploySystem": true,
    "extractPlugins": true,
    "noCheckRPATH": false,
    "qif": true,
    "bin": "pure-qml",
    "qmlDir": "/home/simon/Qt/Examples/Qt-6.1.0/wayland/pure-qml",
    "qmake": "/home/simon/Qt/6.1.0/gcc_64/bin/qmake",
    "targetDir" : "./DeploymentPackage"
}
```

8. Create deployment package for pure-qml: `/snap/cqtdeployer/current/cqtdeployer.sh -confFile deployment.json`

9. Navigate into the deployment package folder (in my case: `/home/simon/Qt/Examples/Qt-6.1.0/wayland/build-pure-qml-Desktop_Qt_6_1_0_GCC_64bit-Debug/DeploymentPackage`)

10. Deploy the pure-qml package:  `./Installerpure-qml.run`, and accept all the defaults in the pop up installation window.

11. Try running the deployed application: `~/pure-qml/pure-qml.sh`. The application failed to run correctly and produced the following error:
```
QML debugging is enabled. Only use this in a safe environment.
QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:60:5: Type CompositorScreen unavailable
qrc:/qml/CompositorScreen.qml:58:5: ListModel is not a type
```

No compositor window was displayed and I had to use Control-C to exit.

**Comment by EndrII** [comment]
> These are the steps I followed when installing the snap version:
> 
>     1. Make sure no other versions of cqtdeployer are installed. i.e. .deb, .run, or snap.
> 
>     2. Download the snap deployment package from: https://github.com/QuasarApp/CQtDeployer/releases/download/1.5.0/cqtdeployer_1.5.0.35_amd64.snap
> 
>     3. Install the cqtdeployer package from the snap file:
> 
> 
> ```
> snap install ~/Downloads/cqtdeployer_1.5.0.35_amd64.snap 
> cqtdeployer 1.5.0.35 from QuasarApp group (quasarrapp) installed
> ```
> 
>     1. Enable permissions for cqtdeployer:
> 
> 
> ```
> sudo snap connect cqtdeployer:process-control
> sudo snap connect cqtdeployer:removable-media
> sudo snap connect cqtdeployer:system-backup
> ```
> 
>     1. Check version of cqtdeployer: `cqtdeployer v`
>        This command didn't work, it produced the error message:
>        `bash: /home/simon/.local/bin/cqtdeployer: No such file or directory`
>        To get this command to work, I had to run: `/snap/cqtdeployer/current/cqtdeployer.sh v`, which produced the output:
> 
> 
> ```
> Info: Print info ...
> CQtDeployer: 1.5.0.35 *** Binary Box ***
> Qt: 5.15.0
> QSettings::setValue: Empty key passed
> ```
> 
>     1. Open Qt creator (Qt6), and open the Qt Wayland pure-qml example. Build the pure-qml application.
> 
>     2. Navigate to the build directory for pure-qml. (in my case: /`home/simon/Qt/Examples/Qt-6.1.0/wayland/build-pure-qml-Desktop_Qt_6_1_0_GCC_64bit-Debug`)
> 
>     3. Create an options JSON file for cqtdeployer: `deployment.json`, as follows:
> 
> 
> ```
> {
>     "clear": true,
>     "deploySystem": true,
>     "extractPlugins": true,
>     "noCheckRPATH": false,
>     "qif": true,
>     "bin": "pure-qml",
>     "qmlDir": "/home/simon/Qt/Examples/Qt-6.1.0/wayland/pure-qml",
>     "qmake": "/home/simon/Qt/6.1.0/gcc_64/bin/qmake",
>     "targetDir" : "./DeploymentPackage"
> }
> ```
> 
>     1. Create deployment package for pure-qml: `/snap/cqtdeployer/current/cqtdeployer.sh -confFile deployment.json`
> 
>     2. Navigate into the deployment package folder (in my case: `/home/simon/Qt/Examples/Qt-6.1.0/wayland/build-pure-qml-Desktop_Qt_6_1_0_GCC_64bit-Debug/DeploymentPackage`)
> 
>     3. Deploy the pure-qml package:  `./Installerpure-qml.run`, and accept all the defaults in the pop up installation window.
> 
>     4. Try running the deployed application: `~/pure-qml/pure-qml.sh`. The application failed to run correctly and produced the following error:
> 
> 
> ```
> QML debugging is enabled. Only use this in a safe environment.
> QQmlApplicationEngine failed to load component
> qrc:/qml/main.qml:60:5: Type CompositorScreen unavailable
> qrc:/qml/CompositorScreen.qml:58:5: ListModel is not a type
> ```
> 
> No compositor window was displayed and I had to use Control-C to exit.

thanks
